/*
 * This file is generated by jOOQ.
 */
package com.ciba.gameoptimizerapi.models.jooq;


import com.ciba.gameoptimizerapi.models.jooq.tables.ComponentCombos;
import com.ciba.gameoptimizerapi.models.jooq.tables.Components;
import com.ciba.gameoptimizerapi.models.jooq.tables.Games;
import com.ciba.gameoptimizerapi.models.jooq.tables.PerformanceFiles;
import com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders;
import com.ciba.gameoptimizerapi.models.jooq.tables.Users;
import com.ciba.gameoptimizerapi.models.jooq.tables.records.PgpArmorHeadersRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamingOptimizer extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>gaming_optimizer</code>
     */
    public static final GamingOptimizer GAMING_OPTIMIZER = new GamingOptimizer();

    /**
     * The table <code>gaming_optimizer.component_combos</code>.
     */
    public final ComponentCombos COMPONENT_COMBOS = ComponentCombos.COMPONENT_COMBOS;

    /**
     * The table <code>gaming_optimizer.components</code>.
     */
    public final Components COMPONENTS = Components.COMPONENTS;

    /**
     * The table <code>gaming_optimizer.games</code>.
     */
    public final Games GAMES = Games.GAMES;

    /**
     * The table <code>gaming_optimizer.performance_files</code>.
     */
    public final PerformanceFiles PERFORMANCE_FILES = PerformanceFiles.PERFORMANCE_FILES;

    /**
     * The table <code>gaming_optimizer.pgp_armor_headers</code>.
     */
    public final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>gaming_optimizer.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>gaming_optimizer.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>gaming_optimizer.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>gaming_optimizer.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private GamingOptimizer() {
        super("gaming_optimizer", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            ComponentCombos.COMPONENT_COMBOS,
            Components.COMPONENTS,
            Games.GAMES,
            PerformanceFiles.PERFORMANCE_FILES,
            PgpArmorHeaders.PGP_ARMOR_HEADERS,
            Users.USERS
        );
    }
}
