/*
 * This file is generated by jOOQ.
 */
package com.ciba.gameoptimizerapi.models.jooq;


import com.ciba.gameoptimizerapi.models.jooq.tables.ComponentCombos;
import com.ciba.gameoptimizerapi.models.jooq.tables.Components;
import com.ciba.gameoptimizerapi.models.jooq.tables.Games;
import com.ciba.gameoptimizerapi.models.jooq.tables.PerformanceFiles;
import com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders;
import com.ciba.gameoptimizerapi.models.jooq.tables.Users;
import com.ciba.gameoptimizerapi.models.jooq.tables.records.PgpArmorHeadersRecord;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;


/**
 * Convenience access to all tables in gaming_optimizer.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>gaming_optimizer.component_combos</code>.
     */
    public static final ComponentCombos COMPONENT_COMBOS = ComponentCombos.COMPONENT_COMBOS;

    /**
     * The table <code>gaming_optimizer.components</code>.
     */
    public static final Components COMPONENTS = Components.COMPONENTS;

    /**
     * The table <code>gaming_optimizer.games</code>.
     */
    public static final Games GAMES = Games.GAMES;

    /**
     * The table <code>gaming_optimizer.performance_files</code>.
     */
    public static final PerformanceFiles PERFORMANCE_FILES = PerformanceFiles.PERFORMANCE_FILES;

    /**
     * The table <code>gaming_optimizer.pgp_armor_headers</code>.
     */
    public static final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>gaming_optimizer.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>gaming_optimizer.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>gaming_optimizer.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return com.ciba.gameoptimizerapi.models.jooq.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>gaming_optimizer.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
