/*
 * This file is generated by jOOQ.
 */
package com.ciba.gameoptimizerapi.models.jooq.tables.records;


import com.ciba.gameoptimizerapi.models.jooq.tables.ComponentCombos;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComponentCombosRecord extends UpdatableRecordImpl<ComponentCombosRecord> implements Record5<UUID, UUID, UUID, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gaming_optimizer.component_combos.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>gaming_optimizer.component_combos.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>gaming_optimizer.component_combos.processor_id</code>.
     */
    public void setProcessorId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>gaming_optimizer.component_combos.processor_id</code>.
     */
    public UUID getProcessorId() {
        return (UUID) get(1);
    }

    /**
     * Setter for
     * <code>gaming_optimizer.component_combos.graphics_card_id</code>.
     */
    public void setGraphicsCardId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>gaming_optimizer.component_combos.graphics_card_id</code>.
     */
    public UUID getGraphicsCardId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>gaming_optimizer.component_combos.ram_id</code>.
     */
    public void setRamId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>gaming_optimizer.component_combos.ram_id</code>.
     */
    public UUID getRamId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>gaming_optimizer.component_combos.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>gaming_optimizer.component_combos.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, UUID, UUID, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, UUID, UUID, UUID, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return ComponentCombos.COMPONENT_COMBOS.ID;
    }

    @Override
    public Field<UUID> field2() {
        return ComponentCombos.COMPONENT_COMBOS.PROCESSOR_ID;
    }

    @Override
    public Field<UUID> field3() {
        return ComponentCombos.COMPONENT_COMBOS.GRAPHICS_CARD_ID;
    }

    @Override
    public Field<UUID> field4() {
        return ComponentCombos.COMPONENT_COMBOS.RAM_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return ComponentCombos.COMPONENT_COMBOS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getProcessorId();
    }

    @Override
    public UUID component3() {
        return getGraphicsCardId();
    }

    @Override
    public UUID component4() {
        return getRamId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getProcessorId();
    }

    @Override
    public UUID value3() {
        return getGraphicsCardId();
    }

    @Override
    public UUID value4() {
        return getRamId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public ComponentCombosRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ComponentCombosRecord value2(UUID value) {
        setProcessorId(value);
        return this;
    }

    @Override
    public ComponentCombosRecord value3(UUID value) {
        setGraphicsCardId(value);
        return this;
    }

    @Override
    public ComponentCombosRecord value4(UUID value) {
        setRamId(value);
        return this;
    }

    @Override
    public ComponentCombosRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ComponentCombosRecord values(UUID value1, UUID value2, UUID value3, UUID value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComponentCombosRecord
     */
    public ComponentCombosRecord() {
        super(ComponentCombos.COMPONENT_COMBOS);
    }

    /**
     * Create a detached, initialised ComponentCombosRecord
     */
    public ComponentCombosRecord(UUID id, UUID processorId, UUID graphicsCardId, UUID ramId, LocalDateTime createdAt) {
        super(ComponentCombos.COMPONENT_COMBOS);

        setId(id);
        setProcessorId(processorId);
        setGraphicsCardId(graphicsCardId);
        setRamId(ramId);
        setCreatedAt(createdAt);
    }
}
