/*
 * This file is generated by jOOQ.
 */
package com.ciba.gameoptimizerapi.models.jooq.tables.records;


import com.ciba.gameoptimizerapi.models.jooq.enums.ComponentType;
import com.ciba.gameoptimizerapi.models.jooq.tables.Components;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ComponentsRecord extends UpdatableRecordImpl<ComponentsRecord> implements Record5<UUID, String, ComponentType, Float, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gaming_optimizer.components.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>gaming_optimizer.components.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>gaming_optimizer.components.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gaming_optimizer.components.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gaming_optimizer.components.type</code>.
     */
    public void setType(ComponentType value) {
        set(2, value);
    }

    /**
     * Getter for <code>gaming_optimizer.components.type</code>.
     */
    public ComponentType getType() {
        return (ComponentType) get(2);
    }

    /**
     * Setter for <code>gaming_optimizer.components.capacity</code>.
     */
    public void setCapacity(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>gaming_optimizer.components.capacity</code>.
     */
    public Float getCapacity() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>gaming_optimizer.components.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>gaming_optimizer.components.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, ComponentType, Float, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, ComponentType, Float, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Components.COMPONENTS.ID;
    }

    @Override
    public Field<String> field2() {
        return Components.COMPONENTS.NAME;
    }

    @Override
    public Field<ComponentType> field3() {
        return Components.COMPONENTS.TYPE;
    }

    @Override
    public Field<Float> field4() {
        return Components.COMPONENTS.CAPACITY;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Components.COMPONENTS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public ComponentType component3() {
        return getType();
    }

    @Override
    public Float component4() {
        return getCapacity();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public ComponentType value3() {
        return getType();
    }

    @Override
    public Float value4() {
        return getCapacity();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public ComponentsRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public ComponentsRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public ComponentsRecord value3(ComponentType value) {
        setType(value);
        return this;
    }

    @Override
    public ComponentsRecord value4(Float value) {
        setCapacity(value);
        return this;
    }

    @Override
    public ComponentsRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public ComponentsRecord values(UUID value1, String value2, ComponentType value3, Float value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ComponentsRecord
     */
    public ComponentsRecord() {
        super(Components.COMPONENTS);
    }

    /**
     * Create a detached, initialised ComponentsRecord
     */
    public ComponentsRecord(UUID id, String name, ComponentType type, Float capacity, LocalDateTime createdAt) {
        super(Components.COMPONENTS);

        setId(id);
        setName(name);
        setType(type);
        setCapacity(capacity);
        setCreatedAt(createdAt);
    }
}
