/*
 * This file is generated by jOOQ.
 */
package com.ciba.gameoptimizerapi.models.jooq.tables.records;


import com.ciba.gameoptimizerapi.models.jooq.tables.Games;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamesRecord extends UpdatableRecordImpl<GamesRecord> implements Record5<UUID, String, Integer, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gaming_optimizer.games.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>gaming_optimizer.games.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>gaming_optimizer.games.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gaming_optimizer.games.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gaming_optimizer.games.year_release</code>.
     */
    public void setYearRelease(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>gaming_optimizer.games.year_release</code>.
     */
    public Integer getYearRelease() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>gaming_optimizer.games.minimum_components_id</code>.
     */
    public void setMinimumComponentsId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>gaming_optimizer.games.minimum_components_id</code>.
     */
    public UUID getMinimumComponentsId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>gaming_optimizer.games.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>gaming_optimizer.games.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, String, Integer, UUID, LocalDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<UUID, String, Integer, UUID, LocalDateTime> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Games.GAMES.ID;
    }

    @Override
    public Field<String> field2() {
        return Games.GAMES.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Games.GAMES.YEAR_RELEASE;
    }

    @Override
    public Field<UUID> field4() {
        return Games.GAMES.MINIMUM_COMPONENTS_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Games.GAMES.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getYearRelease();
    }

    @Override
    public UUID component4() {
        return getMinimumComponentsId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getYearRelease();
    }

    @Override
    public UUID value4() {
        return getMinimumComponentsId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreatedAt();
    }

    @Override
    public GamesRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public GamesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public GamesRecord value3(Integer value) {
        setYearRelease(value);
        return this;
    }

    @Override
    public GamesRecord value4(UUID value) {
        setMinimumComponentsId(value);
        return this;
    }

    @Override
    public GamesRecord value5(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public GamesRecord values(UUID value1, String value2, Integer value3, UUID value4, LocalDateTime value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamesRecord
     */
    public GamesRecord() {
        super(Games.GAMES);
    }

    /**
     * Create a detached, initialised GamesRecord
     */
    public GamesRecord(UUID id, String name, Integer yearRelease, UUID minimumComponentsId, LocalDateTime createdAt) {
        super(Games.GAMES);

        setId(id);
        setName(name);
        setYearRelease(yearRelease);
        setMinimumComponentsId(minimumComponentsId);
        setCreatedAt(createdAt);
    }
}
