/*
 * This file is generated by jOOQ.
 */
package com.ciba.gameoptimizerapi.models.jooq.tables.records;


import com.ciba.gameoptimizerapi.models.jooq.enums.UserType;
import com.ciba.gameoptimizerapi.models.jooq.tables.Users;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record6<UUID, String, String, UserType, UUID, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>gaming_optimizer.users.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>gaming_optimizer.users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>gaming_optimizer.users.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>gaming_optimizer.users.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>gaming_optimizer.users.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>gaming_optimizer.users.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>gaming_optimizer.users.role</code>.
     */
    public void setRole(UserType value) {
        set(3, value);
    }

    /**
     * Getter for <code>gaming_optimizer.users.role</code>.
     */
    public UserType getRole() {
        return (UserType) get(3);
    }

    /**
     * Setter for <code>gaming_optimizer.users.component_combo_id</code>.
     */
    public void setComponentComboId(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>gaming_optimizer.users.component_combo_id</code>.
     */
    public UUID getComponentComboId() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>gaming_optimizer.users.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>gaming_optimizer.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<UUID, String, String, UserType, UUID, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<UUID, String, String, UserType, UUID, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Users.USERS.ID;
    }

    @Override
    public Field<String> field2() {
        return Users.USERS.USERNAME;
    }

    @Override
    public Field<String> field3() {
        return Users.USERS.PASSWORD;
    }

    @Override
    public Field<UserType> field4() {
        return Users.USERS.ROLE;
    }

    @Override
    public Field<UUID> field5() {
        return Users.USERS.COMPONENT_COMBO_ID;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Users.USERS.CREATED_AT;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getUsername();
    }

    @Override
    public String component3() {
        return getPassword();
    }

    @Override
    public UserType component4() {
        return getRole();
    }

    @Override
    public UUID component5() {
        return getComponentComboId();
    }

    @Override
    public LocalDateTime component6() {
        return getCreatedAt();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getUsername();
    }

    @Override
    public String value3() {
        return getPassword();
    }

    @Override
    public UserType value4() {
        return getRole();
    }

    @Override
    public UUID value5() {
        return getComponentComboId();
    }

    @Override
    public LocalDateTime value6() {
        return getCreatedAt();
    }

    @Override
    public UsersRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public UsersRecord value2(String value) {
        setUsername(value);
        return this;
    }

    @Override
    public UsersRecord value3(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UsersRecord value4(UserType value) {
        setRole(value);
        return this;
    }

    @Override
    public UsersRecord value5(UUID value) {
        setComponentComboId(value);
        return this;
    }

    @Override
    public UsersRecord value6(LocalDateTime value) {
        setCreatedAt(value);
        return this;
    }

    @Override
    public UsersRecord values(UUID value1, String value2, String value3, UserType value4, UUID value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(UUID id, String username, String password, UserType role, UUID componentComboId, LocalDateTime createdAt) {
        super(Users.USERS);

        setId(id);
        setUsername(username);
        setPassword(password);
        setRole(role);
        setComponentComboId(componentComboId);
        setCreatedAt(createdAt);
    }
}
